### ISSUE TITLE
[Feature] Improve Readability by Using Margin Shorthand Property

### ISSUE THREAD

**Issue by theslowdeveloper** [creativecommons/cc-resource-archive#137]
## Problem
The current style.css code uses separate properties for `margin-left` `margin-right` , `margin-top` and `margin-bottom` when it could use the `margin` shorthand property to achieve the same effect. Using the shorthand property can make the code more concise and easier to read.

## Description
For example, the following code:

```css
#downloadbuttonholder {
height: 100px;
margin-left: auto;
margin-right: auto;
margin-top: 10px;
margin-bottom: 10px;
}
```

Could be rewritten using the `margin` shorthand property as:

```css
#downloadbuttonholder {
height: 100px;
margin: 10px auto;
}
```

## Implementation
- [x] I would be interested in implementing this feature.
