### ISSUE TITLE
[Feature] Redesign the Thumbnaillist.

### ISSUE THREAD

**Issue by rototrash** [creativecommons/cc-resource-archive#174]
## Problem

The present design of the Thumbnaillist is basic and isn't visually appealing.

## Description
The Thumbnaillist display's a list of resource article's in a basic, unformatted format that is not visually appealing or intuitive for most of the users. To address this , I suggest implementing the following changes:

1. Improved Styling: I will redesign the thumbnailist and it's other elements to make them visually more pleasing and visually engaging, this will involve changing font and providing specific elements with a different font styles to help properly distinguish different elements. Adding shadows and hover effects, and improving the spacing and layout of the elements.
2. Improved Image Display: I will add support for larger responsive images and enable them to be displayed in more prominent position, this will make it easier for user's to browse the resources.
3.Also adding a Date element would help users to access the article from specific periods.

overall even if this changes might seem smaller would have a greater impact on the overall user experience.
 

## Alternatives
The current design of the thumbnail box is 
<img width="729" alt="design" src="https://user-images.githubusercontent.com/86878145/233354566-37e76a95-da16-4a1c-8c36-d5882d778541.png">

I would propose adding shadows to make them more defined and also changing the font style to something that is more aesthetically pleasing and fits the style also add a few more features such a writer's name and also Date elements.

expected outcome for the redesign :

<img width="332" alt="con112" src="https://user-images.githubusercontent.com/86878145/233354932-53a849b6-75d8-4aaa-be5b-e91fc2806b37.png">

## Additional context
I have written a sample code for the possible outcome and would like if it could be reviewed and guided.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by rototrash** [comment]
@possumbilities @TimidRobot can you please check this out?

**Comment by rototrash** [comment]
1. Changing the HTML format of every thumbnail box.
2. Adding "article-writer" and "date" div elements.
3. Improving existing CSS adding a different div element "article-content" to make a specific div category for text related part of the thumbnailbox.
4. Adding optional Hover on the Thumbnailbox
 
```html
<!--thumbnail-container-->
    <div class="thumbnaillist">
        <div class="thumbnailbox {{ page.topic }} {{ page.medium }} {{page.language}}">
            <!--image-container-->
            <div class="thumbnail"><img src="url('{{ page.image-thumb }}')"></div>
            <div class="article-content">
            <h2 class="article-writer">Article Writer</h2>
            <h1 class="thumbnailtitle">{{ page.title }}</h1>
            <!--content -->
            <p class="thumbnailblurb">{{ page.blurb }}</p>
            <p class="date">DD/YY/MM</p>
            </div>
    </div>
    </div>
    </div>
``` 
CSS changes 
```css
.thumbnailbox{
    border: 1px solid #e3e3e3;
    border-radius: 0.5rem;
    width: 260px;
    height: 400px;
    background-color: #fff;
    margin: auto;
    box-shadow: 0 2px 20px rgba(0,0,0, 0.1);
    transition: all 0.6s ease;
    }
    .article-writer{
    font-size: 0.8rem;
    opacity: 0.5;
    }
    .thumbnail{
  background-size: cover;
  max-width: 100%;
 }
 img{
 
 background-size: cover;
 border-radius: 0.5rem 0.5rem 0rem 0rem;
 max-width: 100%;
 margin: auto;
 
}
.thumbnailtitle{
    font-size: 1.2rem;
    font-family: 'IBM Plex Sans';
    margin: auto;
    padding-bottom: 10px;
}
.article-content{
    overflow: hidden;
    display: flex;
    flex-direction: column;
    padding: 16px;
    min-height: 180px;
   padding-top: 0px;
 
}

.thumbnailblurb{
    font-size: 0.8rem;
    font-style: italic;
    position: relative;
    color:#666666 ;
    margin: auto;

}
.date{
    font-size: 0.8rem;
    align-items: flex-start;
    color: #666666;
    
}
```
