### ISSUE TITLE
[Bug] CSS style sheet needs some basic default styles to make the styles consistent

### ISSUE THREAD

**Issue by Biki-das** [creativecommons/cc-resource-archive#32]
## Description

The current stylesheet in the `docs/style.css` needs a small amount of default styles to ensure we don't include the browser default styles

it should start with something like:-

```css
*.
::after.
:::before{
margin:0;
padding:0;
box-sizing: border-box;
}

```

## Reproduction

the `tyle.css `need some resetting

## Resolution
- [x] I would be interested in resolving this bug.
